apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy51
  labels:
    app: autodeploy51
  namespace: namespace-workflow-1708424022813
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy51
  template:
    metadata:
      labels:
        app: autodeploy51
    spec:
      containers:
        - name: autodeploy51
          image: acrworkflow1708424022813.azurecr.io/image-workflow-1708424022813:latest
          ports:
            - containerPort: 5000